### ISSUE TITLE
Improve shareability of the code

### ISSUE THREAD

**Issue by wandadk** [RETURN-project/BenchmarkRecovery#2]
The code is likely not that easy to run for an outsider, so shareability should be improved. 

Some ideas:
- create readme files
- improve documentation
- make sure that code is not dependent of path to local files
- make sure the workflow is clear (eg create a main R file)
- add some example data

**Comment by PabRod** [comment]
Hi Wanda,

having some example data will indeed be quite useful for me. **Can you share some?**

I also suggest structuring the whole repo as a **standard R project**. It is not much more complicated than using any other folder structure and has lots of advantages related to the five points you mention. I can help with that. Let's talk about it in our next meeting and/or via Skype.

Thanks in advance!

**Comment by wandadk** [comment]
Hi Pablo,

I added sampled NBR time series to [this folder](https://github.com/RETURN-project/Simulation/tree/master/Data/SampledData). These time series are used to derive time series characteristics ([this script),](https://github.com/RETURN-project/Simulation/blob/master/Benchmarking/Char_opt_TS.ipynb) that are subsequently used to simulate time series ([this script](https://github.com/RETURN-project/Simulation/blob/master/Benchmarking/Simulate_TS.ipynb)). Recovery indicators can be derived from the simulated time series using [this script](https://github.com/RETURN-project/Simulation/blob/master/Benchmarking/calc_recovery.ipynb).

Yes, sure! Thanks for the suggestion. I'll already check the R project structure!

Let me know if something is not completely clear.

**Comment by PabRod** [comment]
Some advances in adapting to best practices:

- Continuous integration using `Travis CI` since 7f65e8055aa06b6f8ca0ec797cd72b000d700cd0
- Integrated with `codecov` since 6ec5b0e774f5d888bd37df6f645351722628ed4a
- Added lifecycle badge since 38f0931ae1e11eb87291d0a28085ca7b1034664b

The corresponding badges have been appended to `README.md`.

@wandadk: the [codecov report](https://codecov.io/gh/RETURN-project/BenchmarkRecovery) is particularly useful. It tells us what lines of the code have been visited by the tests.

**Comment by PabRod** [comment]
As I said: good work! :)
